# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncui', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_table',
        ),
    ]
